# Generated by Django 5.2.7 on 2025-11-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='Text', unique=True)),
                ('stage', models.CharField(choices=[('LOBBY', 'Lobby'), ('VOTING', 'Voting'), ('ROUND', 'Round')], default='LOBBY')),
                ('character', models.CharField(default='Character')),
                ('current_round', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'rooms',
                'indexes': [models.Index(fields=['code'], name='room_code')],
                'constraints': [models.UniqueConstraint(fields=('code',), name='unique_room_code')],
            },
        ),
    ]
