# Generated by Django 5.2.7 on 2025-11-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='character',
            field=models.CharField(blank=True, null=True),
        ),
    ]
